services:
  db:
    image: mysql:8.4.7
    command: --skip-log-bin --sql-mode=NO_ENGINE_SUBSTITUTION
    ports:
      - "3313:3306"
    volumes:
      - hendyco-db:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=${DB_DATABASE}

volumes:
  hendyco-db:
